### ISSUE TITLE
Hydra shut down after a race condition

### ISSUE THREAD

**Issue by sredxny** [ory/hydra#1141]
Hello, I have Hydra executing in a server with docker. The installation have some months so, it's not updated and honestly I cannot find the version anywhere.

Today I found out that the service was down, I checked the logs and this is what I get:

```
fatal error: concurrent map read and map write

goroutine 1548134 [running]:
runtime.throw(0xddb07b, 0x21)
	/usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc420677160 sp=0xc420677140
runtime.mapaccess2(0xd10100, 0xc420272ed0, 0xc420c53220, 0x76fd5c, 0xc4201cc0b0)
	/usr/local/go/src/runtime/hashmap.go:377 +0x244 fp=0xc4206771a8 sp=0xc420677160
reflect.mapaccess(0xd10100, 0xc420272ed0, 0xc420c53220, 0xc420272ed0)
	/usr/local/go/src/runtime/hashmap.go:1128 +0x3f fp=0xc4206771e0 sp=0xc4206771a8
reflect.Value.MapIndex(0xd10100, 0xc42014ec70, 0x195, 0xcdf620, 0xc420c53220, 0x86, 0xcdf560, 0xc42060a4c8, 0x82)
	/usr/local/go/src/reflect/value.go:1058 +0x128 fp=0xc420677268 sp=0xc4206771e0
encoding/json.(*mapEncoder).encode(0xc4204b0138, 0xc4201cc0b0, 0xd10100, 0xc42014ec70, 0x195, 0x20100)
	/usr/local/go/src/encoding/json/encode.go:690 +0x534 fp=0xc4206773d8 sp=0xc420677268
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd10100, 0xc42014ec70, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc420677418 sp=0xc4206773d8
encoding/json.(*structEncoder).encode(0xc4203f75c0, 0xc4201cc0b0, 0xdabbc0, 0xc420052150, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:645 +0x253 fp=0xc420677578 sp=0xc420677418
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xdabbc0, 0xc420052150, 0x199, 0xc420050100)
	/usr/local/go/src/encoding/json/encode.go:659 +0x64 fp=0xc4206775b8 sp=0xc420677578
encoding/json.(*ptrEncoder).encode(0xc4204b02e0, 0xc4201cc0b0, 0xda9660, 0xc420052150, 0x16, 0xda0100)
	/usr/local/go/src/encoding/json/encode.go:786 +0xe3 fp=0xc4206775f8 sp=0xc4206775b8
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xda9660, 0xc420052150, 0x16, 0xc420050100)
	/usr/local/go/src/encoding/json/encode.go:791 +0x64 fp=0xc420677638 sp=0xc4206775f8
encoding/json.(*encodeState).reflectValue(0xc4201cc0b0, 0xda9660, 0xc420052150, 0x16, 0xc420050100)
	/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc420677670 sp=0xc420677638
encoding/json.interfaceEncoder(0xc4201cc0b0, 0xd027c0, 0xc4205f96c0, 0x94, 0xc420550100)
	/usr/local/go/src/encoding/json/encode.go:617 +0xdb fp=0xc4206776b0 sp=0xc420677670
encoding/json.(*mapEncoder).encode(0xc4204b0030, 0xc4201cc0b0, 0xd129e0, 0xc42062e490, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:690 +0x589 fp=0xc420677820 sp=0xc4206776b0
encoding/json.(*mapEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd129e0, 0xc42062e490, 0x195, 0x100)
	/usr/local/go/src/encoding/json/encode.go:706 +0x64 fp=0xc420677860 sp=0xc420677820
encoding/json.(*structEncoder).encode(0xc4203f64e0, 0xc4201cc0b0, 0xd81ea0, 0xc42062e480, 0x199, 0xc4201c0100)
	/usr/local/go/src/encoding/json/encode.go:645 +0x253 fp=0xc4206779c0 sp=0xc420677860
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd81ea0, 0xc42062e480, 0x199, 0xc420620100)
	/usr/local/go/src/encoding/json/encode.go:659 +0x64 fp=0xc420677a00 sp=0xc4206779c0
encoding/json.(*ptrEncoder).encode(0xc4204b0110, 0xc4201cc0b0, 0xd1aa20, 0xc42062e480, 0x16, 0xd10100)
	/usr/local/go/src/encoding/json/encode.go:786 +0xe3 fp=0xc420677a40 sp=0xc420677a00
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd1aa20, 0xc42062e480, 0x16, 0xc420620100)
	/usr/local/go/src/encoding/json/encode.go:791 +0x64 fp=0xc420677a80 sp=0xc420677a40
encoding/json.(*encodeState).reflectValue(0xc4201cc0b0, 0xd1aa20, 0xc42062e480, 0x16, 0xc420620100)
	/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc420677ab8 sp=0xc420677a80
encoding/json.interfaceEncoder(0xc4201cc0b0, 0xd027c0, 0xc420610000, 0x194, 0xd00100)
	/usr/local/go/src/encoding/json/encode.go:617 +0xdb fp=0xc420677af8 sp=0xc420677ab8
encoding/json.(*arrayEncoder).encode(0xc4204b0048, 0xc4201cc0b0, 0xcd4f20, 0xc4203fe428, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:767 +0xf5 fp=0xc420677b50 sp=0xc420677af8
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xcd4f20, 0xc4203fe428, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:774 +0x64 fp=0xc420677b90 sp=0xc420677b50
encoding/json.(*sliceEncoder).encode(0xc4204b0050, 0xc4201cc0b0, 0xcd4f20, 0xc4203fe428, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:741 +0xc1 fp=0xc420677bd0 sp=0xc420677b90
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xcd4f20, 0xc4203fe428, 0x197, 0x100)
	/usr/local/go/src/encoding/json/encode.go:753 +0x64 fp=0xc420677c10 sp=0xc420677bd0
encoding/json.(*structEncoder).encode(0xc4203f6240, 0xc4201cc0b0, 0xd54320, 0xc4203fe420, 0x199, 0x100)
	/usr/local/go/src/encoding/json/encode.go:645 +0x253 fp=0xc420677d70 sp=0xc420677c10
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd54320, 0xc4203fe420, 0x199, 0xc4203f0100)
	/usr/local/go/src/encoding/json/encode.go:659 +0x64 fp=0xc420677db0 sp=0xc420677d70
encoding/json.(*ptrEncoder).encode(0xc4204b0078, 0xc4201cc0b0, 0xd1a7a0, 0xc4203fe420, 0x16, 0xd10100)
	/usr/local/go/src/encoding/json/encode.go:786 +0xe3 fp=0xc420677df0 sp=0xc420677db0
encoding/json.(*ptrEncoder).(encoding/json.encode)-fm(0xc4201cc0b0, 0xd1a7a0, 0xc4203fe420, 0x16, 0xc4203f0100)
	/usr/local/go/src/encoding/json/encode.go:791 +0x64 fp=0xc420677e30 sp=0xc420677df0
encoding/json.(*encodeState).reflectValue(0xc4201cc0b0, 0xd1a7a0, 0xc4203fe420, 0x16, 0x100)
	/usr/local/go/src/encoding/json/encode.go:323 +0x82 fp=0xc420677e68 sp=0xc420677e30
encoding/json.(*encodeState).marshal(0xc4201cc0b0, 0xd1a7a0, 0xc4203fe420, 0xc428ca0100, 0x0, 0x0)
	/usr/local/go/src/encoding/json/encode.go:296 +0xb8 fp=0xc420677ea0 sp=0xc420677e68
encoding/json.Marshal(0xd1a7a0, 0xc4203fe420, 0x130bd40, 0xc4205e7c60, 0x18, 0x12e1a40, 0xc42043e000)
	/usr/local/go/src/encoding/json/encode.go:161 +0x6e fp=0xc420677ee8 sp=0xc420677ea0
github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).send(0xc42042c000, 0xc420610000, 0x1, 0xfa, 0x12d8f40, 0xc420016220)
	/go/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:285 +0x155 fp=0xc420677f78 sp=0xc420677ee8
github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).sendAsync.func1(0xc42042c000, 0xc420610000, 0x1, 0xfa)
	/go/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:261 +0x4d fp=0xc420677fc0 sp=0xc420677f78
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420677fc8 sp=0xc420677fc0
created by github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).sendAsync
	/go/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:270 +0xed

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7f8e1ce02f68, 0x72, 0x0)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420052848, 0x72, 0x0, 0xc4200c8580)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420052848, 0xffffffffffffffff, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).accept(0xc4200527e0, 0x0, 0x12dacc0, 0xc4200c8580)
	/usr/local/go/src/net/fd_unix.go:430 +0x1e5
net.(*TCPListener).accept(0xc4203f4060, 0xc4204a3680, 0x701c9f, 0xdf6660)
	/usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc4203f4060, 0x6d7ef9, 0xc4202810c0, 0xd028e0)
	/usr/local/go/src/net/tcpsock.go:215 +0x49
net/http.tcpKeepAliveListener.Accept(0xc4203f4060, 0x70c2db, 0xc4204a36d8, 0x9a911e, 0x72ec30)
	/usr/local/go/src/net/http/server.go:3044 +0x2f
crypto/tls.(*listener).Accept(0xc4202b68c0, 0xdf5ef8, 0xc420281040, 0x12e16c0, 0xc4203f66c0)
	/usr/local/go/src/crypto/tls/tls.go:52 +0x37
net/http.(*Server).Serve(0xc4201cc9a0, 0x12dfd80, 0xc4202b68c0, 0x0, 0x0)
	/usr/local/go/src/net/http/server.go:2643 +0x228
net/http.(*Server).ListenAndServeTLS(0xc4201cc9a0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/server.go:2870 +0x31b
github.com/ory/hydra/cmd/server.RunHost.func1.1(0x18, 0xdf5588)
	/go/src/github.com/ory/hydra/cmd/server/handler.go:102 +0x20b
github.com/ory/hydra/vendor/github.com/ory/graceful.Graceful(0xc4202b6740, 0xc4201420f0, 0xc42027fa20, 0x1)
	/go/src/github.com/ory/hydra/vendor/github.com/ory/graceful/http_graceful.go:54 +0xa2
github.com/ory/hydra/cmd/server.RunHost.func1(0x12c8fa0, 0x1328810, 0x0, 0x0)
	/go/src/github.com/ory/hydra/cmd/server/handler.go:106 +0x8fd
github.com/ory/hydra/vendor/github.com/spf13/cobra.(*Command).execute(0x12c8fa0, 0x1328810, 0x0, 0x0, 0x12c8fa0, 0x1328810)
	/go/src/github.com/ory/hydra/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/ory/hydra/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x12cbc40, 0x1328ac0, 0xc420018090, 0xdc5bbe)
	/go/src/github.com/ory/hydra/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/ory/hydra/vendor/github.com/spf13/cobra.(*Command).Execute(0x12cbc40, 0xc42019ff30, 0x75d625)
	/go/src/github.com/ory/hydra/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/ory/hydra/cmd.Execute()
	/go/src/github.com/ory/hydra/cmd/root.go:47 +0xd5
main.main()
	/go/src/github.com/ory/hydra/main.go:18 +0xc2

goroutine 17 [syscall, 156435 minutes, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [syscall, 156435 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 6 [chan receive, 156435 minutes]:
database/sql.(*DB).connectionOpener(0xc4202a4280)
	/usr/local/go/src/database/sql/sql.go:837 +0x4a
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:582 +0x212

goroutine 14 [sleep, 6 minutes]:
time.Sleep(0x45d964b800)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/ory/hydra/metrics.(*MetricsManager).TickKeepAlive(0xc420052150)
	/go/src/github.com/ory/hydra/metrics/middleware.go:85 +0x2d5
created by github.com/ory/hydra/cmd/server.RunHost.func1
	/go/src/github.com/ory/hydra/cmd/server/handler.go:76 +0xd9d

goroutine 13 [sleep]:
time.Sleep(0xd18c2e2800)
	/usr/local/go/src/runtime/time.go:59 +0xf9
github.com/ory/hydra/metrics.(*MetricsManager).CommitTelemetry(0xc420052150)
	/go/src/github.com/ory/hydra/metrics/middleware.go:91 +0x42
created by github.com/ory/hydra/cmd/server.RunHost.func1
	/go/src/github.com/ory/hydra/cmd/server/handler.go:75 +0xd78

goroutine 39 [chan receive, 156435 minutes]:
github.com/ory/hydra/vendor/github.com/ory/graceful.Graceful.func1(0xc42028b500, 0xc4201420f0, 0xc42028b560)
	/go/src/github.com/ory/hydra/vendor/github.com/ory/graceful/http_graceful.go:40 +0x9e
created by github.com/ory/hydra/vendor/github.com/ory/graceful.Graceful
	/go/src/github.com/ory/hydra/vendor/github.com/ory/graceful/http_graceful.go:51 +0x98

goroutine 40 [select, 156435 minutes, locked to thread]:
runtime.gopark(0xdf6528, 0x0, 0xdc317c, 0x6, 0x18, 0x2)
	/usr/local/go/src/runtime/proc.go:271 +0x13a
runtime.selectgoImpl(0xc420035f50, 0x0, 0x18)
	/usr/local/go/src/runtime/select.go:423 +0x1364
runtime.selectgo(0xc420035f50)
	/usr/local/go/src/runtime/select.go:238 +0x1c
runtime.ensureSigM.func1()
	/usr/local/go/src/runtime/signal_unix.go:434 +0x2dd
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1

goroutine 200 [select]:
github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).loop(0xc42042c000)
	/go/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:338 +0xaa0
created by github.com/ory/hydra/vendor/github.com/segmentio/analytics-go.(*Client).startLoop
	/go/src/github.com/ory/hydra/vendor/github.com/segmentio/analytics-go/analytics.go:232 +0x3f

goroutine 1548049 [select]:
net/http.(*http2serverConn).serve(0xc42043e000)
	/usr/local/go/src/net/http/h2_bundle.go:3554 +0xa64
net/http.(*http2Server).ServeConn(0xc4203f6570, 0x12e43c0, 0xc4205be380, 0xc4204a7d30)
	/usr/local/go/src/net/http/h2_bundle.go:3187 +0x7cd
net/http.http2ConfigureServer.func1(0xc4201cc9a0, 0xc4205be380, 0x12dc2c0, 0xc42027a310)
	/usr/local/go/src/net/http/h2_bundle.go:3065 +0x8f
net/http.(*conn).serve(0xc420281040, 0x12e16c0, 0xc4203f66c0)
	/usr/local/go/src/net/http/server.go:1746 +0xff8
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce

goroutine 1548064 [IO wait]:
net.runtime_pollWait(0x7f8e1c934190, 0x72, 0x6)
	/usr/local/go/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201b8068, 0x72, 0x12dc700, 0x12d7078)
	/usr/local/go/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201b8068, 0xc420132c00, 0x400)
	/usr/local/go/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201b8000, 0xc420132c00, 0x400, 0x400, 0x0, 0x12dc700, 0x12d7078)
	/usr/local/go/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4204b0000, 0xc420132c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc4205ca120, 0x7f8e1ce030e8, 0xc4204b0000, 0x5, 0xc4204b0000, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc4205be380, 0xdf6617, 0xc4205be4a0, 0x2)
	/usr/local/go/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc4205be380, 0xc42026f218, 0x9, 0x9, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:1134 +0x11d
io.ReadAtLeast(0x7f8e1cc2f180, 0xc4205be380, 0xc42026f218, 0x9, 0x9, 0x9, 0xc420452aa0, 0xc420cdaa70, 0xc4200547c0)
	/usr/local/go/src/io/io.go:307 +0xa9
io.ReadFull(0x7f8e1cc2f180, 0xc4205be380, 0xc42026f218, 0x9, 0x9, 0xc420039f44, 0x2, 0x2)
	/usr/local/go/src/io/io.go:325 +0x58
net/http.http2readFrameHeader(0xc42026f218, 0x9, 0x9, 0x7f8e1cc2f180, 0xc4205be380, 0x0, 0xc400000000, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:781 +0x7b
net/http.(*http2Framer).ReadFrame(0xc42026f1e0, 0xc42051e960, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:1008 +0xa4
net/http.(*http2serverConn).readFrames(0xc42043e000)
	/usr/local/go/src/net/http/h2_bundle.go:3443 +0xab
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:3548 +0x305

goroutine 1548063 [select]:
net/http.(*http2serverConn).awaitGracefulShutdown(0xc42043e000, 0xc420012de0, 0xc4202cc060)
	/usr/local/go/src/net/http/h2_bundle.go:3595 +0x102
created by net/http.(*http2serverConn).serve
	/usr/local/go/src/net/http/h2_bundle.go:3544 +0xc47
```

I was checking to know if this was reported before but I didn't find anything, so, am wondering, this is already fixed in the updates?
The situation is that is unknown on how to replicate the error and is difficult that I debug it in the last version of hydra.

Thank you very much!

**Comment by aeneasr** [comment]
I suppose this happened with beta.9?

**Comment by sredXNY** [comment]
@aeneasr hello, is there a way to find the version? I can tell you that I installed it like 11-12 months ago

**Comment by aeneasr** [comment]
`hydra version`. I see, is that not the latest version?

**Comment by sredXNY** [comment]
@aeneasr correct, it's not the last version. I entered to the container to check the version but I get:

```
/go/src/github.com/ory/hydra # hydra version
Version:    dev-master
Git Hash:   undefined
Build Time: 2018-10-31 21:00:38.848791968 +0000 UTC
```

**Comment by aeneasr** [comment]
Ok, that's definitely an older version because that was a bug in the container build system which was fixed at least a couple of months ago. I think `docker ps` should show you all the running containers and the name+tag (e.g. `oryd/hydra:v0.10.0`)

I also think that I can recall an error in that particular place of the server which has been fixed since then. I'm closing this because I'm pretty sure it has been fixed but please keep the details coming!

**Comment by aeneasr** [comment]
Nevermind, let's reopen it and find the issue. Any bit of info helps!

**Comment by sredXNY** [comment]
@aeneasr ok, thank you very much. Then I think that I will proceed with the migration to the updated version. I will maintain informed if this happen again. Again, thanks!

**Comment by aeneasr** [comment]
Ok, closing this again but feel free to reopen any time you encounter this.
