### ISSUE TITLE
nil pointer panic on /oauth2/sessions/logout without id token hint

### ISSUE THREAD

**Issue by MDrollette** [ory/hydra#1403]
**Describe the bug**

Hydra crashes with a nil pointer panic on requests to  the public endpoint`/oauth2/sessions/logout`

**To Reproduce**
1. Have an active login session
1. Make a GET request from a user-agent to `/oauth2/sessions/logout`

**Expected behavior**

I believe the expected behavior is that the login session should be revoked and the cookies deleted and the user-agent redirected to the `urls.post_logout_redirect`. Instead the request fails with a nil pointer panic.

**Version:**
 - docker
 - v1.0.0-rc.10

**Additional context**

This [LogoutRequest](https://github.com/ory/hydra/blob/master/consent/strategy_default.go#L749) is created without a `Client` field set.

Then this [subsequent method](https://github.com/ory/hydra/blob/master/consent/sql_helper.go#L152) is called which assumes the `Client` is non-nil causing a nil pointer panic.

```
{"level":"info","method":"GET","msg":"started handling request","remote":"172.18.0.19:57878","request":"/oauth2/sessions/logout","time":"2019-04-30T04:27:31Z"}
2019/04/30 04:27:31 http: panic serving 172.18.0.19:57878: runtime error: invalid memory address or nil pointer dereference
goroutine 1173 [running]:
net/http.(*conn).serve.func1(0xc000555860)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0xdb6780, 0x1722ad0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/ory/hydra/consent.newSQLLogoutRequest(...)
	/go/src/github.com/ory/hydra/consent/sql_helper.go:152
github.com/ory/hydra/consent.(*SQLManager).CreateLogoutRequest(0xc000548ea0, 0x1040340, 0xc00053e7b0, 0xc000373780, 0xc00033c500, 0x0)
	/go/src/github.com/ory/hydra/consent/manager_sql.go:551 +0x10b
github.com/ory/hydra/consent.(*DefaultStrategy).issueLogoutVerifier(0xc000548ec0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0x1767ea0, 0x174a5e0, 0x7fe419eb1550)
	/go/src/github.com/ory/hydra/consent/strategy_default.go:749 +0x514
github.com/ory/hydra/consent.(*DefaultStrategy).HandleOpenIDConnectLogout(0xc000548ec0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0x7fe419eb1550, 0xc0002e5400, 0x40bde9)
	/go/src/github.com/ory/hydra/consent/strategy_default.go:939 +0x73
github.com/ory/hydra/oauth2.(*Handler).LogoutHandler(0xc0003e5e20, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0x0, 0x0, 0x0)
	/go/src/github.com/ory/hydra/oauth2/handler.go:123 +0x72
github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc0004b5300, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/julienschmidt/httprouter@v1.2.0/router.go:334 +0x948
github.com/urfave/negroni.Wrap.func1(0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b00c0)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc000352e00, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b00c0)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1027a60, 0xc000352e00, 0xc000352ec0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/go/src/net/http/server.go:1995
github.com/ory/hydra/x.RejectInsecureRequests.func1(0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b00a0)
	/go/src/github.com/ory/hydra/x/tls_termination.go:55 +0x9e
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc0000966c0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b00a0)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1027a60, 0xc0000966c0, 0xc000352ea0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/ory/x/metricsx.(*Service).ServeHTTP(0xc000544780, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b0080)
	/go/pkg/mod/github.com/ory/x@v0.0.53/metricsx/middleware.go:260 +0x92
github.com/urfave/negroni.middleware.ServeHTTP(0x1025ee0, 0xc000544780, 0xc000352e80, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/ory/hydra/metrics/prometheus.(*MetricsManager).ServeHTTP(0xc0000aa430, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b0040)
	/go/src/github.com/ory/hydra/metrics/prometheus/middleware.go:26 +0x44
github.com/urfave/negroni.middleware.ServeHTTP(0x1024ba0, 0xc0000aa430, 0xc000352e60, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/meatballhat/negroni-logrus.(*Middleware).ServeHTTP(0xc0001aeba0, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300, 0xc0004b0000)
	/go/pkg/mod/github.com/meatballhat/negroni-logrus@v0.0.0-20170801195057-31067281800f/middleware.go:136 +0x27a
github.com/urfave/negroni.middleware.ServeHTTP(0x10249e0, 0xc0001aeba0, 0xc000352e40, 0x7fe419ef0028, 0xc00011c008, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc0003aee40, 0x103d480, 0xc0002c81c0, 0xc00056a300)
	/go/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xec
net/http.serverHandler.ServeHTTP(0xc0002d00d0, 0x103d480, 0xc0002c81c0, 0xc00056a300)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc000555860, 0x1040280, 0xc000295d00)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
```

**Comment by aeneasr** [comment]
Interesting, e2e tests didn't catch this. The client-id is actually set by the consent request. Maybe there is some consistency issue going on?

Could you maybe add steps to reproduce this exact issue? It would greatly help with debugging. It should be reproducable in an incognito window!

**Comment by aeneasr** [comment]
Oh I misread - yeah good point with your finding!

**Comment by es-lab** [comment]
@aeneasr I'm having this issue too with the latest version.
I tried to add a fix
```
func newSQLLogoutRequest(c *LogoutRequest) *sqlLogoutRequest {
	var clientID string
	if c.Client != nil {
		clientID = c.Client.ClientID
	}
	return &sqlLogoutRequest{
		Challenge:             c.Challenge,
		Verifier:              c.Verifier,
		Subject:               c.Subject,
		SessionID:             c.SessionID,
		RequestURL:            c.RequestURL,
		PostLogoutRedirectURI: c.PostLogoutRedirectURI,
		WasUsed:               c.WasUsed,
		Accepted:              c.Accepted,
		Client:                clientID,
		RPInitiated:           c.RPInitiated,
	}
}
```

But it fails later when inserting into the table with the following error: 
```
time="2019-04-30T15:13:05Z" level=error msg="An error occurred" error="pq: insert or update on table \"hydra_oauth2_logout_request\" violates foreign key constraint \"hydra_oauth2_logout_request_client_id_fk\"
```

I don't know if you started working on this or not, but I'm kinda stuck with using this version and can't(don't want to) rollback because of too many changes that are done and pushed to the stage environment.

Thank you.

**Comment by MDrollette** [comment]
@es-lab are you able to use the RP-initiated logout flow (https://www.ory.sh/docs/hydra/oauth2#logout)? That is how I am working around it.

**Comment by es-lab** [comment]
@MDrollette I'm not using OIDC, so I do not have any ID Token to use. This workaround would require me to setup additional stuff to generate the ID Token and manage it, to then just send it in the logout hint param... too much!

**Comment by aeneasr** [comment]
We'll roll out a fix this week
