### ISSUE TITLE
Connection refused on localhost

### ISSUE THREAD

**Issue by lukaswanner** [ory/hydra#2688]
**Describe the bug**

Im trying to implement the login and consent screen. I started with clone the repo at https://github.com/ory/hydra-login-consent-node.  I followd the guide at https://www.ory.sh/hydra/docs/guides/login

I then changed the settings for the hydra docker container to fit the login and consent node app. 
The app is running at localhost:3000 and hydra is running at localhost:9000. So I configured the settings with the following command:

`docker run -d --name ory-hydra-example--hydra --network hydraguide -p 9000:4444 -p 9001:4445 -e SECRETS_SYSTEM=$SECRETS_SYSTEM -e DSN=$DSN -e URLS_SELF_ISSUER=https://localhost:9000/ -e URLS_CONSENT=http://localhost:3000/consent -e URLS_LOGIN=http://localhost:3000/login oryd/hydra:v1.10.5 serve all
`

After starting up the container and accessing the login page under localhost:3000/login I get the following error:

`{ "message": "connect ECONNREFUSED 127.0.0.1:80", "name": "Error", "stack": "Error: connect ECONNREFUSED 127.0.0.1:80\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)", "config": { "url": "http://localhost/oauth2/auth/requests/login?login_challenge=undefined", "method": "get", "headers": { "Accept": "application/json, text/plain, */*", "User-Agent": "axios/0.19.2" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 }, "code": "ECONNREFUSED" }`

**Reproducing the bug**
Set up the hydra docker and set up the login/consent node app. Start both and go over to /login. You get the errormessage mentioned above

I will just list all the commands i ran for the docker container in case i set some wrong flags.

`export SECRETS_SYSTEM=$(export LC_CTYPE=C; cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1) `

`export DSN=postgres://hydra:secret@ory-hydra-example--postgres:5432/hydra?sslmode=disable`

`docker pull oryd/hydra:v1.10.5`

`docker run -it --rm --network hydraguide oryd/hydra:v1.10.5 migrate sql --yes $DSN`

`docker run -d --name ory-hydra-example--hydra --network hydraguide -p 9000:4444 -p 9001:4445 -e SECRETS_SYSTEM=$SECRETS_SYSTEM -e DSN=$DSN -e URLS_SELF_ISSUER=https://localhost:9000/ -e URLS_CONSENT=http://localhost:3000/consent -e URLS_LOGIN=http://localhost:3000/login oryd/hydra:v1.10.5 serve all`

_Server logs_

`{ "message": "connect ECONNREFUSED 127.0.0.1:80", "name": "Error", "stack": "Error: connect ECONNREFUSED 127.0.0.1:80\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)", "config": { "url": "http://localhost/oauth2/auth/requests/login?login_challenge=undefined", "method": "get", "headers": { "Accept": "application/json, text/plain, */*", "User-Agent": "axios/0.19.2" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 }, "code": "ECONNREFUSED" }`

_Server configuration_

standard settings for the hydra container see commans above.

**Expected behavior**

I can start a login flow/ access the login/consent page

**Environment**

- Version: hydra:v1.10.5 and latest https://github.com/ory/hydra-login-consent-node
- Environment: Windows

**Additional context**

**Comment by lukaswanner** [comment]
closed since i just had to change the basePath in config.ts.
