### ISSUE TITLE
migration fails first time (postgres)

### ISSUE THREAD

**Issue by ToonvanStrijp** [ory/hydra#2709]
**Describe the bug**

We're using postgres for our hydra instance. During setup we noticed that the migration always fails the first.

```
Could not apply migrations:
unexpected EOF
problem checking for migration version 20190400000010000000
```

**Reproducing the bug**

1. Create a postgres database (we use the zalando postgres operator)
2. Enable the `autoMigrate` option in the hydra helm chart
3. Install the helm chart with your custom values.yaml file.
4. A migrate job get created.
5. See the logs of this pod, as you can see it's stuck with all migrations having status `pending`.

_Server logs_

```
time=2021-09-02T08:44:37Z level=info msg=No tracer configured - skipping tracing setup audience=application service_name=ORY Hydra service_version=v1.10.5
The following migration is planned:

Version                Name                                              Status    
20190100000001000000   client                                            Pending   
20190100000002000000   client                                            Pending   
20190100000003000000   client                                            Pending   
20190100000004000000   client                                            Pending   
20190100000005000000   client                                            Pending   
20190100000006000000   client                                            Pending   
20190100000007000000   client                                            Pending   
20190100000008000000   client                                            Pending   
20190100000009000000   client                                            Pending   
20190100000010000000   client                                            Pending   
20190100000011000000   client                                            Pending   
20190100000012000000   client                                            Pending   
20190100000013000000   client                                            Pending   
20190100000014000000   client                                            Pending   
20190200000001000000   jwk                                               Pending   
20190200000002000000   jwk                                               Pending   
20190200000003000000   jwk                                               Pending   
20190200000004000000   jwk                                               Pending   
20190300000001000000   consent                                           Pending   
20190300000002000000   consent                                           Pending   
20190300000003000000   consent                                           Pending   
20190300000004000000   consent                                           Pending   
20190300000005000000   consent                                           Pending   
20190300000006000000   consent                                           Pending   
20190300000007000000   consent                                           Pending   
20190300000008000000   consent                                           Pending   
20190300000009000000   consent                                           Pending   
20190300000010000000   consent                                           Pending   
20190300000011000000   consent                                           Pending   
20190300000012000000   consent                                           Pending   
20190300000013000000   consent                                           Pending   
20190300000014000000   consent                                           Pending   
20190400000001000000   oauth2                                            Pending   
20190400000002000000   oauth2                                            Pending   
20190400000003000000   oauth2                                            Pending   
20190400000004000000   oauth2                                            Pending   
20190400000005000000   oauth2                                            Pending   
20190400000006000000   oauth2                                            Pending   
20190400000007000000   oauth2                                            Pending   
20190400000008000000   oauth2                                            Pending   
20190400000009000000   oauth2                                            Pending   
20190400000010000000   oauth2                                            Pending   
20190400000011000000   oauth2                                            Pending   
20200521071434000000   consent                                           Pending   
20200527215731000000   client                                            Pending   
20200527215732000000   client                                            Pending   
20200819163013000000   add_client_id_subject_idx_to_access_and_refresh   Pending   
20200913192340000000   initial_sqlite                                    Pending   
20201110104000000000   drop_uq_oauth2                                    Pending   
20201116133000000000   set_null_time                                     Pending   
Could not apply migrations:
unexpected EOF
error committing or rolling back transaction: %!s(<nil>)
github.com/ory/x/popx.(*Migrator).isolatedTransaction
	/go/pkg/mod/github.com/ory/x@v0.0.276/popx/migrator.go:320
github.com/ory/x/popx.(*Migrator).UpTo.func1
	/go/pkg/mod/github.com/ory/x@v0.0.276/popx/migrator.go:136
github.com/ory/x/popx.(*Migrator).exec
	/go/pkg/mod/github.com/ory/x@v0.0.276/popx/migrator.go:558
github.com/ory/x/popx.(*Migrator).UpTo
	/go/pkg/mod/github.com/ory/x@v0.0.276/popx/migrator.go:90
github.com/ory/x/popx.(*Migrator).Up
	/go/pkg/mod/github.com/ory/x@v0.0.276/popx/migrator.go:78
github.com/ory/hydra/persistence/sql.(*Persister).MigrateUp
	/home/ory/persistence/sql/persister_migration.go:40
github.com/ory/hydra/cmd/cli.(*MigrateHandler).MigrateSQL
	/home/ory/cmd/cli/handler_migrate.go:107
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/ory/hydra/cmd.Execute
	/home/ory/cmd/root.go:87
main.main
	/home/ory/main.go:33
runtime.main
	/usr/local/go/src/runtime/proc.go:225
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1371
Successfully applied migrations!
```

_Server configuration_

```
  hydra:
    autoMigrate: true
    dangerousForceHttp: true
    serve:
      tls:
        allow_termination_from:
          - "127.0.0.1/32"
    config:
      ttl:
        id_token: 168h
        access_token: 168h
        refresh_token: 336h
      urls:
        self:
          issuer: "http://10.0.2.2:9080/hydra"
        login: "http://10.0.2.2:9080/auth/login"
        consent: "http://10.0.2.2:9080/auth/consent"
    existingSecret: hydra-secret
  maester:
    enabled: false
```

**Expected behavior**

I would expect that migrations to run successfully without the need of running it twice.

**Environment**

- Version: v1.10.5
- Environment: Kubernetes (k3d)

**Comment by ToonvanStrijp** [comment]
@aeneasr This is my DSN: `postgres://hydra:ayEfJeUyQ3AmCfraMMwog7WR9mSwPgMnGKxeYsCkzhwy5G9UYg69XcbWnMjQLbAI@acid-hydra-database:5432/hydra`

**Comment by aeneasr** [comment]
Thank you - so the database is running in the cluster? Is there maybe some connection issue to the cluster? For example, k3d is using lots of resources, causing MySQL to become slow and potentially kill a connection sometimes (hence EOF). Because this behavior doesn't look like it's the fault of Hydra.

Also which MySQL version are you using, and, is the error consistently reproducible. Meaning, it's always the same migration failing.

Also, please share the MySQL error logs (although I am not good at debugging MySQL so this might be an exercise left to the reader)

**Comment by ToonvanStrijp** [comment]
@aeneasr I'm using postgres version 13. And I think you're right about the resource problem. The machine I'm running this on isn't that powerful. If I take a look at the database logs.

```
2021-09-02 09:27:25,885 INFO: no action. I am (acid-hydra-database-0) the leader with the lock
2021-09-02 09:27:35,873 INFO: no action. I am (acid-hydra-database-0) the leader with the lock
2021-09-02 09:27:53.251 92 LOG {ticks: 0, maint: 0, retry: 0}
2021-09-02 09:28:23.280 92 LOG {ticks: 0, maint: 0, retry: 0}
2021-09-02 09:28:53.302 92 LOG {ticks: 0, maint: 0, retry: 0}
2021-09-02 09:29:23.319 92 LOG {ticks: 0, maint: 0, retry: 0}
2021-09-02 09:27:45,818 INFO: Lock owner: acid-hydra-database-0; I am acid-hydra-database-0
2021-09-02 09:29:52,120 WARNING: Retry got exception: 'connection problems'
/var/run/postgresql:5432 - rejecting connections
2021-09-02 09:29:52,226 ERROR: Exception when called state_handler.last_operation()
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/patroni/ha.py", line 151, in update_lock
    last_lsn = self.state_handler.last_operation()
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 962, in last_operation
    return self._wal_position(self.is_leader(), self._cluster_info_state_get('wal_position'),
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 372, in is_leader
    return bool(self._cluster_info_state_get('timeline'))
  File "/usr/local/lib/python3.6/dist-packages/patroni/postgresql/__init__.py", line 349, in _cluster_info_state_get
    raise PostgresConnectionException(self._cluster_info_state['error'])
patroni.exceptions.PostgresConnectionException: "'Exceeded retry deadline'"
2021-09-02 09:29:52,329 INFO: Error communicating with PostgreSQL. Will try again later
2021-09-02 09:29:52,331 WARNING: Loop time exceeded, rescheduling immediately.
/var/run/postgresql:5432 - rejecting connections
2021-09-02 09:29:52,402 INFO: Lock owner: acid-hydra-database-0; I am acid-hydra-database-0
2021-09-02 09:29:52,413 INFO: establishing a new patroni connection to the postgres cluster
2021-09-02 09:29:52,593 INFO: establishing a new patroni connection to the postgres cluster
2021-09-02 09:29:52,602 WARNING: Retry got exception: 'connection problems'
2021-09-02 09:29:52,658 INFO: PostgreSQL is still starting up, 300 seconds until timeout
2021-09-02 09:29:53.349 92 LOG {ticks: 0, maint: 0, retry: 0}
/var/run/postgresql:5432 - accepting connections
2021-09-02 09:30:02,910 INFO: Lock owner: acid-hydra-database-0; I am acid-hydra-database-0
2021-09-02 09:30:02,911 INFO: establishing a new patroni connection to the postgres cluster
2021-09-02 09:30:03,054 INFO: no action. I am (acid-hydra-database-0) the leader with the lock
2021-09-02 09:30:12,907 INFO: no action. I am (acid-hydra-database-0) the leader with the lock
2021-09-02 09:30:22,848 INFO: no action. I am (acid-hydra-database-0) the leader with the lock
```

So I think we can close this issue, I'll test this on a more powerful machine.

**Comment by aeneasr** [comment]
Nice, thank you for the follow up 👍

**Comment by ToonvanStrijp** [comment]
Tested this on a more powerful machine and it worked all fine. So we can confirm this was indeed a resource limit issue.
