### ISSUE TITLE
[docker-compose] ERROR: for postgresd expected string or buffer

### ISSUE THREAD

**Issue by VRspace4** [ory/hydra#540]
Hi, I'm getting the following error when executing the command `docker-compose up --build` from the latest git clone on a CentOS 7 machine. I tried switching from postgres to mysql and had similar "expected string or buffer" error. Please advise.

```
[root@rm hydra]# docker-compose up --build
WARNING: The LOG_LEVEL variable is not set. Defaulting to a blank string.
WARNING: The ACCESS_TOKEN_LIFESPAN variable is not set. Defaulting to a blank string.
WARNING: The ID_TOKEN_LIFESPAN variable is not set. Defaulting to a blank string.
WARNING: The AUTHORIZE_CODE_LIFESPAN variable is not set. Defaulting to a blank string.
WARNING: Found orphan containers (hydra_mysqld_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Building hydra
Step 1 : FROM golang:1.8-alpine
 ---> 0eb10ccd6a58
Step 2 : RUN apk add --no-cache git build-base
 ---> Using cache
 ---> 3873e713824e
Step 3 : RUN go get github.com/Masterminds/glide
 ---> Using cache
 ---> 1cc60da76056
Step 4 : WORKDIR /go/src/github.com/ory/hydra
 ---> Using cache
 ---> 766281afaa1c
Step 5 : ADD ./glide.yaml ./glide.yaml
 ---> Using cache
 ---> 422d4fbd009d
Step 6 : ADD ./glide.lock ./glide.lock
 ---> Using cache
 ---> aa94ed528fbd
Step 7 : RUN glide install --skip-test -v
 ---> Using cache
 ---> 61357facda36
Step 8 : ADD . .
 ---> Using cache
 ---> 7588a3622b86
Step 9 : RUN go install .
 ---> Using cache
 ---> 6a9c52e23993
Step 10 : ENTRYPOINT /go/bin/hydra migrate sql $DATABASE_URL; /go/bin/hydra host --dangerous-auto-logon --dangerous-force-http --disable-telemetry
 ---> Using cache
 ---> efcead5470ea
Step 11 : EXPOSE 4444
 ---> Using cache
 ---> c77f5d500950
Successfully built c77f5d500950

ERROR: for postgresd  expected string or buffer
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 118, in perform_command
    handler(command, command_options)
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 926, in up
    scale_override=parse_scale_args(options['--scale']),
  File "/usr/lib/python2.7/site-packages/compose/project.py", line 424, in up
    get_deps
  File "/usr/lib/python2.7/site-packages/compose/parallel.py", line 69, in parallel_execute
    raise error_to_reraise
TypeError: expected string or buffer
```

**Comment by arekkas** [comment]
Looks like a docker compose issue, either retry, reinstall docker, or ask in docker github :)
